<?php
// i18n-map.php @generated by automattic/jetpack-composer-plugin
return array(
  'domain' => 'jetpack',
  'type' => 'plugins',
  'packages' => array(
    'jetpack-assets' => '0.0.0',
    'jetpack-tracking' => '0.0.0',
    'jetpack-heartbeat' => '0.0.0',
    'jetpack-password-checker' => '0.0.0',
    'jetpack-idc' => '0.0.0',
    'jetpack-backup-pkg' => '0.0.0',
    'jetpack-connection' => '0.0.0',
    'jetpack-sync' => '0.0.0',
    'jetpack-config' => '0.0.0',
    'jetpack-connection-ui' => '0.0.0',
    'jetpack-jitm' => '0.0.0',
    'jetpack-lazy-images' => '0.0.0',
    'jetpack-licensing' => '0.0.0',
    'jetpack-my-jetpack' => '0.0.0',
    'jetpack-search-pkg' => '0.0.0',
  ),
);
 array(
      'path' => 'jetpack_vendor/automattic/jetpack-password-checker',
      'ver' => '0.2.2',
    ),
    'jetpack-idc' => array(
      'path' => 'jetpack_vendor/automattic/jetpack-identity-crisis',
      'ver' => '0.6.4',
    ),
    'jetpack-sync' => array(
      'path' => 'jetpack_vendor/automattic/jetpack-sync',
      'ver' => '1.29.0',
    ),
    'jetpack-backup-pkg' => array(
      'path' => 'jetpack_vendor/automattic/jetpack-backup',
      'ver' => '1.2.3',
    ),
    'jetpack-config' => array(
      'path' => 'jetpack_vendor/automattic/jetpack-config',
      'ver' => '1.6.0',
    ),
    'jetpack-connection-ui' => array(
      'path' => 'jetpack_vendor/automattic/jetpack-connection-ui',
      'ver' => '2.3.3',
    ),
    'jetpack-jitm' => array(
      'path' => 'jetpack_vendor/automattic/jetpack-jitm',
      'ver' => '2.2.3',
    ),
    'jetpack-lazy-images' => array(
      'path' => 'jetpack_vendor/automattic/jetpack-lazy-images',
      'ver' => '2.1.3',
    ),
    'jetpack-licensing' => array(
      'path' => 'jetpack_vendor/automattic/jetpack-licensing',
      'ver' => '1.6.2',
    ),
    'jetpack-my-jetpack' => array(
      'path' => 'jetpack_vendor/automattic/jetpack-my-jetpack',
      'ver' => '0.4.0',
    ),
    'jetpack-search-pkg' => array(
      'path' => 'jetpack_vendor/automattic/jetpack-search',
      'ver' => '0.5.4',
    ),
  ),
);
