<?php

/**
 * @file
 * Terms and conditions checkout pane.
 *
 * This module is based on the idea and some of the work on
 * http://www.ubercart.org/contrib/877 (qrios et al) in which the author has
 * authorized me to take over/improve the module.
 */

define('UC_TC_DEFAULT_PATH', '');
define('UC_TC_DEFAULT_LIGHTBOX2_WIDTH', 800);
define('UC_TC_DEFAULT_LIGHTBOX2_HEIGHT', 600);

/**
 * Implementation of hook_menu().
 */
function uc_tc_menu() {
  $items['admin/store/settings/uc_tc'] = array(
    'title' => 'Terms and conditions',
    'description' => 'Terms and Conditions settings.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('uc_tc_settings'),
    'access arguments' => array('administer store'),
    'type' => MENU_NORMAL_ITEM,
  );

  return $items;
}

/**
 * Menu callback: Module' settings.
 */
function uc_tc_settings() {
  $form['uc_tc_path'] = array(
    '#type' => 'textfield',
    '#title' => t('Terms and conditions path'),
    '#default_value' => variable_get('uc_tc_path', UC_TC_DEFAULT_PATH),
    '#size' => 40,
    '#description' => t('Enter the drupal path that hold the terms and conditions of the site.'),
    '#field_prefix' => url(NULL, array('absolute' => TRUE)) . (variable_get('clean_url', 0) ? '' : '?q='),
    '#required' => TRUE,
  );

  $form['lightbox2'] = array(
    '#type' => 'fieldset',
    '#title' => 'lightbox2',
    '#description' => t('This settings will be used only if you have <a href="http://drupal.org/project/lightbox2">lightbox2 module</a> installed and enabled. A <b><i>?format=lightbox2</i></b> query string will be appended to the path entered above so you can custimoize the look and feel of that page when viewed inside the lightbox2. Please read <a href="http://drupal.org/node/252260">Lightbox2 - How to add a lightbox to webpage links</a> for further documentation. I chose the alternative query string solution vs the lightbox2 built-in so it can work for other pages than nodes.'),
    '#collapsible' => TRUE,
    '#collapsed' => FALSE,
  );
  $form['lightbox2']['uc_tc_lightbox2_width'] = array(
    '#type' => 'textfield',
    '#title' => t('Width'),
    '#description' => t('The width of the lightbox2 window.'),
    '#default_value' => variable_get('uc_tc_lightbox2_width', UC_TC_DEFAULT_LIGHTBOX2_WIDTH),
  );
  $form['lightbox2']['uc_tc_lightbox2_height'] = array(
    '#type' => 'textfield',
    '#title' => t('Width'),
    '#description' => t('The height of the lightbox2 window.'),
    '#default_value' => variable_get('uc_tc_lightbox2_height', UC_TC_DEFAULT_LIGHTBOX2_HEIGHT),
  );

  return system_settings_form($form);
}

/**
 * Implementation of hook_theme().
 **/
function uc_tc_theme() {
  return array(
    'uc_tc_termconditions_checkbox_label' => array(
      'variables' => array(
        'link_path' => null,
        'lightbox2_width' => null,
        'lightbox2_height' => null
      ),
    ),
  );
}

/*******************************************************************************
* Ubercart Hooks
******************************************************************************/
/**
 * Implementation of hook_uc_checkout_pane().
 */
function uc_tc_uc_checkout_pane() {
  $panes[] = array(
    'id' => 'uc_ct',
    'callback' => 'uc_checkout_pane_termsandconditions',
    'title' => t('Terms and conditions'),
    'desc' => t("A checkbox for for the customer to agree with the site's terms and conditions."),
    'weight' => 10,
    'collapsible' => FALSE,
  );
  return $panes;
}

/**
 * Display the TC Pane
 */
function uc_checkout_pane_termsandconditions($op) {
  switch ($op) {
    case 'view':
      //Show Checkbox
      drupal_add_css(drupal_get_path('module', 'uc_tc').'/uc_tc.css');
      $contents['uc_tc']['agree'] = array(
        '#type' => 'checkboxes',
        '#title' => t('Terms and Conditions'),
        '#options' => array('uc_tc' => theme('uc_tc_termconditions_checkbox_label', array(
           'link_path' => variable_get('uc_tc_path', UC_TC_DEFAULT_PATH),
           'width' => variable_get('uc_tc_lightbox2_width', UC_TC_DEFAULT_LIGHTBOX2_WIDTH),
           'height' => variable_get('uc_tc_lightbox2_height', UC_TC_DEFAULT_LIGHTBOX2_HEIGHT),
        ))),
        '#weight' => 1,
        '#required' => true,
      );
      return array('contents' => $contents, 'next-button' => FALSE);
  }
}

/**
 * Returns a formatted link for the checkbox on the checkout page
 *
 * @param $path
 *   A drupal path to link the "terms and conditions" phrase.
 *   Support for lightbox2 module
 *   
 *
 * @ingroup themeable
 */
function theme_uc_tc_termconditions_checkbox_label($variables) {
  $link_path = $variables['link_path'];
  $width = $variables['width'];
  $height = $variables['height'];
  $link = t('terms and conditions');
  $options = array('attributes' => array('id' => 'uc_tc_checkbox'), 'html' => TRUE);

  if ($link_path) {
    $link_path = drupal_get_normal_path($link_path);
    if (module_exists('lightbox2')) {
      $options['attributes']['rel'] = "lightframe[|width:{$width}px; height: {$height}px;]";
      $options['query'] = array('format' => 'lightbox2');
    } else {
      $options['attributes']['target'] = '_blank';
    }
    $link = l($link, $link_path, $options);
  }

  return t('I agree with the !link.', array('!link' => $link));
}

